export const SidePanelSelectors = {
    searchBox: ".oxd-main-menu-search input",
    adminMenu: "a[href$='viewAdminModule']",
    pimMenu: "a[href$='viewPimModule']",
    leaveMenu: "a[href$='viewLeaveModule']",
    timeMenu: "a[href$='viewTimeModule']",
    recruitmentMenu: "a[href$='viewRecruitmentModule']",
    myDetailsMenu: "a[href$='viewMyDetails']",
    performanceMenu: "a[href$='viewPerformanceModule']",
    dashboardMenu: "a[href$='/dashboard/index']",
    directoryMenu: "a[href$='viewDirectory']",
    maintenanceMenu: "a[href$='viewMaintenanceModule']",
    claimMenu: "a[href$='viewClaimModule']",
    buzzMenu: "a[href$='viewBuzz']",
    rootAllMenu: "[class='oxd-main-menu']",
}

export const SidePanelMenuLabels = [
    "Admin",
    "PIM",
    "Leave",
    "Time",
    "Recruitment",
    "My Info",
    "Performance",
    "Dashboard",
    "Directory",
    "Maintenance",
    "Claim",
    "Buzz",
]