name: Cypress Multi-Browser (Manual Shell)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to test'
        required: false
        default: 'main'
      browsers:
        description: 'Choose a specific browser (optional: chrome/firefox/edge)'
        required: false
        default: ''
      reset_env:
        description: 'Reset environment (clean install)?'
        required: false
        default: 'false'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ${{ fromJson(github.event.inputs.browser != '' && format('["{0}"]', github.event.inputs.browser) || '["chrome", "firefox", "edge"]') }}

    env:
      CYPRESS_BASE_URL: 'https://opensource-demo.orangehrmlive.com'
      BROWSER: ${{ matrix.browser }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Optionally Reset Environment
        if: ${{ github.event.inputs.reset_env == 'true' }}
        run: npm run reset_frw

      - name: Install Dependencies
        if: ${{ github.event.inputs.reset_env != 'true' }}
        run: npm ci

      - name: Prepare Allure Report Folder
        run: npm run prereport

      - name: Run Cypress tests for each selected browser
        run: |
            echo "Running tests on $BROWSER..."
            BROWSER=$BROWSER npm run test || echo "Tests failed on $BROWSER"

      - name: Generate Allure Report
        if: always()
        run: npm run allure:generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/allure-report
